language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
matrix:
  allow_failures:
  - php: '5.3'
  - php: '5.4'
  - php: '5.5'
  - php: hhvm
  - php: nightly

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist